[contract]
stock_id = "2897"

[order]
price = 8.3
quantity = 1
action = "Buy"              # Buy or Sell
price_type = "LMT"          # LMT (限價) or MKT (市價)
order_type = "ROD"          # ROD (當日有效) or IOC (立即成交否則取消) or FOK
order_lot = "Common"        # Common (整股) or IntradayOdd (盤中零股) or Odd (盤後零股) or Fixing(盤後定盤)
order_cond = "Cash"         # Cash (現股) or MarginTrading (融資) or ShortSelling (融券)
