# examples

[trading_hours]
start_time = "08:30"
end_time = "13:30"
interval_seconds = 3

[order]
symbol = "6016"
price = 11.0
quantity = 1
action = "Buy"  # Buy or Sell
price_type = "LMT"  # LMT (限價), MKT (市價), MKP (範圍市價)
order_type = "ROD"  # ROD, IOC, FOK
order_lot = "Common"  # Common (整股), IntradayOdd (盤中零股), Odd (盤後零股), Fixing (定盤)
account_index = 0  # Index of stock account to use

[api]
url = ""
broker_name = "sinotrade-stock-python"

[user]
api_key = ""
secret_key = ""
person_id = ""
